s = C:\Users\ris04\AppData\Roaming\Code\User\snippets\cpp-cp.code-snippets # snippet file address
t = . # template folder address
l = cpp # language

all:
	C:/Users/ris04/AppData/Local/Programs/Python/Python38/python.exe vscode.py -s $s -t $t -l $l

help:
	C:/Users/ris04/AppData/Local/Programs/Python/Python38/python.exe vscode.py -h